language: generic
os: linux
dist: trusty

branches:
  only:
    - master

linux-conan: &linux-conan
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker
  install:
    - .conan/travis/install.sh
  script:
    - .conan/travis/run.sh

osx-conan: &osx-conan
  os: osx
  language: generic
  install:
    - .conan/travis/install.sh
  script:
    - .conan/travis/run.sh

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'g++-7']
      env:
        - CXX=clang++-5.0

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0', 'g++-7']
      env:
        - CXX=clang++-6.0

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'g++-7']
      env:
        - CXX=clang++-7

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'g++-7']
      env:
        - CXX=clang++-7
        - CPPFLAGS=-fms-extensions

    - language: cpp
      os: osx
      osx_image: xcode10
      compiler: clang
      script:
        - $CXX --version
        - make -j3 compile

    - <<: *linux-conan
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

    - <<: *linux-conan
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

    - <<: *linux-conan
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50

    - <<: *linux-conan
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

    - <<: *linux-conan
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

    - <<: *osx-conan
      osx_image: xcode10
      env: CONAN_APPLE_CLANG_VERSIONS=10.0

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --gcov gcov-7 --gcov-options '\-lp' --exclude src/test

script:
  - $CXX --version
  - make -j3
