language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.7']
      env: COMPILER=g++-4.7

# disable due to PostgreSQL REAL datatype problem
#    - os: linux
#      compiler: gcc
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['g++-4.8']
#      env: COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9 CXXSTD=c++14

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5 CXXSTD=c++14

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5 CXXSTD=c++1z

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER=g++-6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER=g++-6 CXXSTD=c++14

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER=g++-6 CXXSTD=c++17

# disable due to problem with akrzemi1/optional
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
#          packages: ['clang-3.5']
#      env: COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER=clang++-3.6 CXXSTD=c++14

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7 CXXSTD=c++14

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env: COMPILER=clang++-3.8

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env: COMPILER=clang++-3.8 CXXSTD=c++14

    - os: osx
      compiler: clang
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ CXXSTD=c++11

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ CXXSTD=c++14

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ CXXSTD=c++1z

    - os: osx
      osx_image: xcode7.1
      compiler: clang
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode7.2
      compiler: clang
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER=clang++

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --gcov gcov-6 --gcov-options '\-lp' --exclude src/test --exclude include/tao/optional/akrzemi1

script:
  make CXX=$COMPILER -j3
